'use strict'; // code generated by pbf v3.2.1

// Player ========================================

var Player = {};

Player.read = function (pbf, end) {
    return pbf.readFields(Player._readField, {id: 0, x: 0, y: 0, angle: 0}, end);
};
Player._readField = function (tag, obj, pbf) {
    if (tag === 1) obj.id = pbf.readVarint();
    else if (tag === 2) obj.x = pbf.readFloat();
    else if (tag === 3) obj.y = pbf.readFloat();
    else if (tag === 4) obj.angle = pbf.readFloat();
};
Player.write = function (obj, pbf) {
    if (obj.id) pbf.writeVarintField(1, obj.id);
    if (obj.x) pbf.writeFloatField(2, obj.x);
    if (obj.y) pbf.writeFloatField(3, obj.y);
    if (obj.angle) pbf.writeFloatField(4, obj.angle);
};

// Snowball ========================================

var Snowball = {};

Snowball.read = function (pbf, end) {
    return pbf.readFields(Snowball._readField, {id: 0, x: 0, y: 0}, end);
};
Snowball._readField = function (tag, obj, pbf) {
    if (tag === 1) obj.id = pbf.readVarint();
    else if (tag === 2) obj.x = pbf.readFloat();
    else if (tag === 3) obj.y = pbf.readFloat();
};
Snowball.write = function (obj, pbf) {
    if (obj.id) pbf.writeVarintField(1, obj.id);
    if (obj.x) pbf.writeFloatField(2, obj.x);
    if (obj.y) pbf.writeFloatField(3, obj.y);
};

// State ========================================

var State = {};

State.read = function (pbf, end) {
    return pbf.readFields(State._readField, {my_last_seq: 0, players: [], snowballs: []}, end);
};
State._readField = function (tag, obj, pbf) {
    if (tag === 1) obj.my_last_seq = pbf.readVarint();
    else if (tag === 2) obj.players.push(Player.read(pbf, pbf.readVarint() + pbf.pos));
    else if (tag === 3) obj.snowballs.push(Snowball.read(pbf, pbf.readVarint() + pbf.pos));
};
State.write = function (obj, pbf) {
    if (obj.my_last_seq) pbf.writeVarintField(1, obj.my_last_seq);
    if (obj.players) for (var i = 0; i < obj.players.length; i++) pbf.writeMessage(2, Player.write, obj.players[i]);
    if (obj.snowballs) for (i = 0; i < obj.snowballs.length; i++) pbf.writeMessage(3, Snowball.write, obj.snowballs[i]);
};

// UserInput ========================================

var UserInput = {};

UserInput.read = function (pbf, end) {
    return pbf.readFields(UserInput._readField, {move_angle: 0, look_angle: 0, input_time: 0, moving: false, shooting: false}, end);
};
UserInput._readField = function (tag, obj, pbf) {
    if (tag === 1) obj.move_angle = pbf.readFloat();
    else if (tag === 2) obj.look_angle = pbf.readFloat();
    else if (tag === 3) obj.input_time = pbf.readFloat();
    else if (tag === 4) obj.moving = pbf.readBoolean();
    else if (tag === 5) obj.shooting = pbf.readBoolean();
};
UserInput.write = function (obj, pbf) {
    if (obj.move_angle) pbf.writeFloatField(1, obj.move_angle);
    if (obj.look_angle) pbf.writeFloatField(2, obj.look_angle);
    if (obj.input_time) pbf.writeFloatField(3, obj.input_time);
    if (obj.moving) pbf.writeBooleanField(4, obj.moving);
    if (obj.shooting) pbf.writeBooleanField(5, obj.shooting);
};
